// Copyright 2024 The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HPCMLPolicySourceApplyConfiguration represents a declarative configuration of the HPCMLPolicySource type for use
// with apply.
type HPCMLPolicySourceApplyConfiguration struct {
	Tasks    *int32            `json:"tasks,omitempty"`
	Manager  *string           `json:"manager,omitempty"`
	Settings map[string]string `json:"settings,omitempty"`
}

// HPCMLPolicySourceApplyConfiguration constructs a declarative configuration of the HPCMLPolicySource type for use with
// apply.
func HPCMLPolicySource() *HPCMLPolicySourceApplyConfiguration {
	return &HPCMLPolicySourceApplyConfiguration{}
}

// WithTasks sets the Tasks field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tasks field is set to the value of the last call.
func (b *HPCMLPolicySourceApplyConfiguration) WithTasks(value int32) *HPCMLPolicySourceApplyConfiguration {
	b.Tasks = &value
	return b
}

// WithManager sets the Manager field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Manager field is set to the value of the last call.
func (b *HPCMLPolicySourceApplyConfiguration) WithManager(value string) *HPCMLPolicySourceApplyConfiguration {
	b.Manager = &value
	return b
}

// WithSettings puts the entries into the Settings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Settings field,
// overwriting an existing map entries in Settings field with the same key.
func (b *HPCMLPolicySourceApplyConfiguration) WithSettings(entries map[string]string) *HPCMLPolicySourceApplyConfiguration {
	if b.Settings == nil && len(entries) > 0 {
		b.Settings = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Settings[k] = v
	}
	return b
}
